datastore: mydb
config:
  driverName: cql
  descriptor: 127.0.0.1?keyspace=mydb&disableInitialHostLookup=true
  params:
    keyspace: mydb
admin:
  datastore: admin
  config:
    driverName: cql
    descriptor: 127.0.0.1?disableInitialHostLookup=true
recreate: true
scripts:
  - URL: config/schema.ddl