Datastore: mydb
Ping: true
Config:
  DriverName: aerospike
  Descriptor: tcp(127.0.0.1:3000)/[namespace]
  Parameters:
    dbname: mydb
    namespace: test
    host: 127.0.0.1
    port: '3000'
    dateFormat: yyyy-MM-dd hh:mm:ss
    keyColumnName: id
Recreate: true
